;; Each new term in the Fibonacci sequence is generated by adding the previous
;; two terms. By starting with 1 and 2, the first 10 terms will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci sequence whose values do not exceed
;; four million, find the sum of the even-valued terms.

(defparameter *limit* (* 4 (expt 10 6)))    ; *limit* = four million

(defun sum-of-even-fibs (limit)
  (let ((sum 0))
    (labels ((fib (n1 n2)
                  (when (< n2 limit)
                    (fib n2 (+ n1 n2)))
                  (when (evenp n1)
                    (setf sum (+ sum n1)))))
      (fib 1 2))
    sum))

(princ (sum-of-even-fibs *limit*))
