;; Each new term in the Fibonacci sequence is generated by adding the previous
;; two terms. By starting with 1 and 2, the first 10 terms will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci sequence whose values do not exceed
;; four million, find the sum of the even-valued terms.

(defconstant +limit+ (* 4 (expt 10 6)))    ; +limit+ = four million

(defun sum-fibs-even (limit)
  (do ((sum 0 (+ sum (if (evenp f2) f2 0)))
       (f1 1 f2)
       (f2 2 (+ f1 f2)))
    ((> f2 limit) sum)))

(princ (sum-fibs-even +limit+))
