-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed
-- four million, find the sum of the even-valued terms.

limit = 4 * 10^6

fibsLim lim = fibsLim' lim [1, 0]
fibsLim' lim fs@(f2:f1:f0)
    | f2 > lim = tail fs
    | otherwise = fibsLim' lim ((f2 + f1):fs)

main = do
    let result = sum [ f | f <- fibsLim limit, odd f ]
    print result
